# DevForge Managed Apache PHP Module Configuration
# Configured for: 8.5
LoadFile "C:/DevForge/bin/php/8.5/libcrypto-3-x64.dll"
LoadFile "C:/DevForge/bin/php/8.5/libssl-3-x64.dll"
LoadFile "C:/DevForge/bin/php/8.5/libsqlite3.dll"
LoadFile "C:/DevForge/bin/php/8.5/libsodium.dll"
LoadFile "C:/DevForge/bin/php/8.5/php8ts.dll"
LoadModule php_module "C:/DevForge/bin/php/8.5/php8apache2_4.dll"
PHPIniDir "C:/DevForge/bin/php/8.5"
<IfModule mime_module>
    AddType application/x-httpd-php .php
</IfModule>
