# DevForge Default MySQL Configuration
[client]
port = 3306

[mysql]
default-character-set = utf8mb4

[mysqld]
port = 3306
basedir = "C:/DevForge/bin/mysql"
datadir = "C:/DevForge/data/mysql"
default_storage_engine = InnoDB
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
max_connections = 100
mysqlx = 0
loose_component_reference_cache = OFF
sql_mode = NO_ENGINE_SUBSTITUTION
log-error = "C:/DevForge/logs/mysql_error.log"
pid-file = "C:/DevForge/data/mysql/mysql.pid"
